# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneid', models.IntegerField()),
                ('taxid', models.IntegerField()),
                ('symbol', models.CharField(max_length=64)),
                ('symbolother', models.CharField(max_length=64, null=True)),
                ('fullname', models.CharField(max_length=256, null=True)),
                ('locustag', models.CharField(max_length=64, null=True)),
                ('synonyms', models.CharField(max_length=256, null=True)),
                ('dbxrefs', models.CharField(max_length=64, null=True)),
                ('chromosome', models.CharField(max_length=16, null=True)),
                ('map_location', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('type_of_gene', models.CharField(max_length=256, null=True)),
                ('nomenclature_status', models.CharField(max_length=256, null=True)),
                ('other_designations', models.CharField(max_length=256, null=True)),
                ('modification_date', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
