version: '2'

services:
  web:
    restart: always
    build: ./web/
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file: env

    # for production, remove the following volumes, ports and command definitions, and uncomment the gunicorn
    volumes:
      - ./web:/web
    ports:
      - "8080:8080"
    command: ./manage.py runserver 0.0.0.0:8080

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql
#      - ./backups/postgresql:/backup
    env_file:
      - env
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

volumes:
  data:

