from flask_wtf import Form
from wtforms import TextAreaField, StringField, BooleanField, SelectField
from wtforms.validators import DataRequired, length
from datetime import datetime

class ExperimentForm(Form):
    saveas = SelectField('Save As')
    name = StringField('Name', validators=[DataRequired(), length(max=128)])
    description = StringField('Description', validators=[DataRequired(), length(max=256)])
    is_public = BooleanField('Make Public', default=False)

class SequenceForm(Form):
    name = StringField('Job Name', validators=[DataRequired(), length(max=128)],
                       default=datetime.isoformat(datetime.now()))
    fasta_sequences = TextAreaField('Sequences (FASTA format)', validators=[DataRequired()], default=">ACTB\n\
ACCGCCGAGACCGCGTCCGCCCCGCGAGCACAGAGCCTCGCCTTTGCCGATCCGCCGCCCGTCCACACCCGCCGCCAGCTCACCATGGATGATGATATCGCCGCGCTCGTCGTCGACAACGGCTCCGGCATGTGCAAGGCCGGCTTCGCGGGCGACGATGCCCCCCGGGCCGTCTTCCCCTCCATCGTGGGGCGCCCCAGGCACCAGGGCGTGATGGTGGGCATGGGTCAGAAGGATTCCTATGTGGGCGACGAGGCCCAGAGCAAGAGAGGCATCCTCACCCTGAAGTACCCCATCGAGCACGGCATCGTCACCAACTGGGACGACATGGAGAAAATCTGGCACCACACCTTCTACAATGAGCTGCGTGTGGCTCCCGAGGAGCACCCCGTGCTGCTGACCGAGGCCCCCCTGAACCCCAAGGCCAACCGCGAGAAGATGACCCAGATCATGTTTGAGACCTTCAACACCCCAGCCATGTACGTTGCTATCCAGGCTGTGCTATCCCTGTACGCCTCTGGCCGTACCACTGGCATCGTGATGGACTCCGGTGACGGGGTCACCCACACTGTGCCCATCTACGAGGGGTATGCCCTCCCCCATGCCATCCTGCGTCTGGACCTGGCTGGCCGGGACCTGACTGACTACCTCATGAAGATCCTCACCGAGCGCGGCTACAGCTTCACCACCACGGCCGAGCGGGAAATCGTGCGTGACATTAAGGAGAAGCTGTGCTACGTCGCCCTGGACTTCGAGCAAGAGATGGCCACGGCTGCTTCCAGCTCCTCCCTGGAGAAGAGCTACGAGCTGCCTGACGGCCAGGTCATCACCATTGGCAATGAGCGGTTCCGCTGCCCTGAGGCACTCTTCCAGCCTTCCTTCCTGGGCATGGAGTCCTGTGGCATCCACGAAACTACCTTCAACTCCATCATGAAGTGTGACGTGGACATCCGCAAAGACCTGTACGCCAACACAGTGCTGTCTGGCGGCACCACCATGTACCCTGGCATTGCCGACAGGATGCAGAAGGAGATCACTGCCCTGGCACCCAGCACAATGAAGATCAAGATCATTGCTCCTCCTGAGCGCAAGTACTCCGTGTGGATCGGCGGCTCCATCCTGGCCTCGCTGTCCACCTTCCAGCAGATGTGGATCAGCAAGCAGGAGTATGACGAGTCCGGCCCCTCCATCGTCCACCGCAAATGCTTCTAGGCGGACTATGACTTAGTTGCGTTACACCCTTTCTTGACAAAACCTAACTTGCGCAGAAAACAAGATGAGATTGGCATGGCTTTATTTGTTTTTTTTGTTTTGTTTTGGTTTTTTTTTTTTTTTTGGCTTGACTCAGGATTTAAAAACTGGAACGGTGAAGGTGACAGCAGTCGGTTGGAGCGAGCATCCCCCAAAGTTCACAATGTGGCCGAGGACTTTGATTGCACATTGTTGTTTTTTTAATAGTCATTCCAAATATGAGATGCGTTGTTACAGGAAGTCCCTTGCCATCCTAAAAGCCACCCCACTTCTCTCTAAGGAGAATGGCCCAGTCCTCTCCCAAGTCCACACAGGGGAGGTGATAGCATTGCTTTCGTGTAAATTATGTAATGCAAAATTTTTTTAATCTTCGCCTTAATACTTTTTTATTTTGTTTTATTTTGAATGATGAGCCTTCGTGCCCCCCCTTCCCCCTTTTTTGTCCCCCAACTTGAGATGTATGAAGGCTTTTGGTCTCCCTGGGAGTGGGTGGAGGCAGCCAGGGCTTACCTGTACACTGACTTGAGACCAGTTGAATAAAAGTGCACACCTTAAAAATGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
    primer3_config_taqman = TextAreaField('Primer3 config (taqman)', validators=[DataRequired()],
                                          default="""PRIMER_TASK=generic
PRIMER_PICK_INTERNAL_OLIGO=1
PRIMER_PRODUCT_SIZE_RANGE=50-400
PRIMER_PRODUCT_OPT_SIZE=66
PRIMER_NUM_RETURN=100
PRIMER_TM_FORMULA=1
PRIMER_EXPLAIN_FLAG=1
PRIMER_OPT_SIZE=20
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=30
PRIMER_OPT_TM=62
PRIMER_MIN_TM=56
PRIMER_MAX_TM=65
PRIMER_OPT_GC_PERCENT=55
PRIMER_MIN_GC=15
PRIMER_MAX_GC=85
PRIMER_MAX_POLY_X=10
PRIMER_INTERNAL_OPT_SIZE=22
PRIMER_INTERNAL_MIN_SIZE=15
PRIMER_INTERNAL_MAX_SIZE=30
PRIMER_INTERNAL_OPT_TM=71
PRIMER_INTERNAL_MIN_TM=67
PRIMER_INTERNAL_MAX_TM=77
PRIMER_INTERNAL_OPT_GC_PERCENT=55
PRIMER_INTERNAL_MIN_GC=15
PRIMER_INTERNAL_MAX_GC=85
PRIMER_INTERNAL_MAX_POLY_X=3
""")
    primer3_config_preamp = TextAreaField('Primer3 config (preamp)', validators=[DataRequired()],
                                          default="""PRIMER_TASK=generic
PRIMER_PICK_INTERNAL_OLIGO=0
PRIMER_PRODUCT_SIZE_RANGE=50-1000
PRIMER_PRODUCT_OPT_SIZE=0
PRIMER_NUM_RETURN=10
PRIMER_TM_FORMULA=1
PRIMER_EXPLAIN_FLAG=1
PRIMER_OPT_SIZE=24
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=30
PRIMER_OPT_TM=62
PRIMER_MIN_TM=56
PRIMER_MAX_TM=68
PRIMER_OPT_GC_PERCENT=55
PRIMER_MIN_GC=15
PRIMER_MAX_GC=85
PRIMER_MAX_POLY_X=3
""")